# Generated by Django 2.0.7 on 2019-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='payload',
            field=models.CharField(max_length=1000),
        ),
    ]
