# Generated by Django 2.0.7 on 2019-09-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20190831_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='payload',
        ),
    ]
